apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://9.30.44.17:8001
  name: mycluster
contexts:
- context:
    cluster: mycluster
    namespace: default
    user: admin
  name: mycluster-context
current-context: mycluster-context
kind: Config
preferences: {}
users:
- name: admin
  user:
    token: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdF9oYXNoIjoiNWMzMTIxOWIwNTFiMGY2YjkwZWM3M2VmYWRjZWNkMjUxNjVlMjAwOCIsInJlYWxtTmFtZSI6ImN1c3RvbVJlYWxtIiwidW5pcXVlU2VjdXJpdHlOYW1lIjoiYWRtaW4iLCJpc3MiOiJodHRwczovL215Y2x1c3Rlci5pY3A6OTQ0My9vaWRjL2VuZHBvaW50L09QIiwiYXVkIjoiMGQ5Y2YyZDEyNTdkMDJhMTA0ZGU0NDkxODE5ZjIzMWMiLCJleHAiOjE1NjI4NTE0OTgsImlhdCI6MTU2MjgyMjY5OCwic3ViIjoiYWRtaW4iLCJ0ZWFtUm9sZU1hcHBpbmdzIjpbXX0.gJUuSQXyHEbzvqLg2pdOfElK70x2Y0SeB9Q3yGUYxy3YDU363EkuJSKEJSRCkJyntrk4uOS4pCDpZeuSj3hw5osfM5bjZyv9fNHSkiEoVrkpo7dW4Sov2HvxPzhIDn9D9vkustzyfwzlbsUTwCWeUPmpJ59CQku9-2amiCe18lbID0vFwIsm8t4RBMfmTcK0sAOYQItWWRLyTVID-aMbTYRmkSXVN5uxRXl7XwhYUrrKf2BElHVAJkP27ChSh9qHFyT7RCKIe5oNcJv-TGo-5FQ6JW_yy6-NhN05UDHt3bjrJsKJqvm9sutc_O5GH2C_45AByUdqxeTbtPRDEPhSYA
- name: user1
  user:
    token: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdF9oYXNoIjoiODgyODQzOWUxMGViM2VlYjgzYWY2MDhlY2ZjNTQ0NWZkZTg0ZTU3YSIsInJlYWxtTmFtZSI6ImN1c3RvbVJlYWxtIiwidW5pcXVlU2VjdXJpdHlOYW1lIjoidXNlcjEiLCJpc3MiOiJodHRwczovL215Y2x1c3Rlci5pY3A6OTQ0My9vaWRjL2VuZHBvaW50L09QIiwiYXVkIjoiZDdiNTg4ODI3ZmU4NzZmYjY0NzQyZjc1Mjk4MTNjNDAiLCJleHAiOjE1NTg2MTU2OTgsImlhdCI6MTU1ODU4Njg5OCwic3ViIjoidXNlcjEiLCJ0ZWFtUm9sZU1hcHBpbmdzIjpbImljcDp0ZWFtLXVzZXItMTphZG1pbiIsImljcDpkZWZhdWx0Om1lbWJlciIsImljcDpkZWZhdWx0OnRlYW1hZG1pbiJdfQ.HujBYeyVSF-1I9ymTO8r3ERsuimlFSaqWUEH6hk6XqROtF1JDueCXhhwOQWwDxqWJdambGE_M3RZj3NO7heTdeIYejKKhK8Ga1GeBVekRoMz72q2dckErAHgfbYGOwP1q2Z3uittqwGLznt8VFY07Ggedfpjh5kSqChEIhKeP1gDzfM-R2v6kqVjg4J5x8X5qGI8uhbvflg18FCASKJQXtnpRTncJsdycl7VA55byrvK7FRJaJA10yJhTGVmdTqWDygtu3bkPKVPMQPuHzBIflJ-mylM0n2PCQdLAJaW9q99EzTPnGoiB43NjXHpiGZj3arS4J6CIrffErKfTqhGwA
