apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://9.30.44.17:8001
  name: mycluster
contexts:
- context:
    cluster: mycluster
    namespace: default
    user: admin
  name: mycluster-context
current-context: mycluster-context
kind: Config
preferences: {}
users:
- name: admin
  user:
    token: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdF9oYXNoIjoiOGQ0ZWI0OTUzYmYxOWQ2YjVjMTA4YmY3MDI4ZDk3YzZmZjZmNjg4NyIsInJlYWxtTmFtZSI6ImN1c3RvbVJlYWxtIiwidW5pcXVlU2VjdXJpdHlOYW1lIjoiYWRtaW4iLCJpc3MiOiJodHRwczovL215Y2x1c3Rlci5pY3A6OTQ0My9vaWRjL2VuZHBvaW50L09QIiwiYXVkIjoiMGQ5Y2YyZDEyNTdkMDJhMTA0ZGU0NDkxODE5ZjIzMWMiLCJleHAiOjE1NjI3MjMyNjcsImlhdCI6MTU2MjY5NDQ2Nywic3ViIjoiYWRtaW4iLCJ0ZWFtUm9sZU1hcHBpbmdzIjpbXX0.oTIhTbwGnI_9c61nsbQIOMlTnPZxkjIF3mmMrjQSDEMwHGPIuqhGYGPcSPZBVh4jJkjD3lITh9U9xSXlRtQGYn5hIMDzQe2TuRD2cihsxflvofPFEcOGmavf5Z5zBM7KxRQdv4wRvVou1shsfNpdOr_OPmSTwFTiayhlYrKsaE6jbwHGpwCi_zUG_T0plGNBNaftYpdxg2O01iptdd7LHQFx2nvrO7PQ2nVeuyafmuRyCULWsQu8bLZmPa9PHTJIK9VTZNbV5UOCUGXH4MGw-BaAsKHT54gngdplr1nF1L8QVu1GDUASy-m2EE2OR-JBwDd4tcBuhnrXvaYOaXrkow
- name: user1
  user:
    token: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdF9oYXNoIjoiODgyODQzOWUxMGViM2VlYjgzYWY2MDhlY2ZjNTQ0NWZkZTg0ZTU3YSIsInJlYWxtTmFtZSI6ImN1c3RvbVJlYWxtIiwidW5pcXVlU2VjdXJpdHlOYW1lIjoidXNlcjEiLCJpc3MiOiJodHRwczovL215Y2x1c3Rlci5pY3A6OTQ0My9vaWRjL2VuZHBvaW50L09QIiwiYXVkIjoiZDdiNTg4ODI3ZmU4NzZmYjY0NzQyZjc1Mjk4MTNjNDAiLCJleHAiOjE1NTg2MTU2OTgsImlhdCI6MTU1ODU4Njg5OCwic3ViIjoidXNlcjEiLCJ0ZWFtUm9sZU1hcHBpbmdzIjpbImljcDp0ZWFtLXVzZXItMTphZG1pbiIsImljcDpkZWZhdWx0Om1lbWJlciIsImljcDpkZWZhdWx0OnRlYW1hZG1pbiJdfQ.HujBYeyVSF-1I9ymTO8r3ERsuimlFSaqWUEH6hk6XqROtF1JDueCXhhwOQWwDxqWJdambGE_M3RZj3NO7heTdeIYejKKhK8Ga1GeBVekRoMz72q2dckErAHgfbYGOwP1q2Z3uittqwGLznt8VFY07Ggedfpjh5kSqChEIhKeP1gDzfM-R2v6kqVjg4J5x8X5qGI8uhbvflg18FCASKJQXtnpRTncJsdycl7VA55byrvK7FRJaJA10yJhTGVmdTqWDygtu3bkPKVPMQPuHzBIflJ-mylM0n2PCQdLAJaW9q99EzTPnGoiB43NjXHpiGZj3arS4J6CIrffErKfTqhGwA
